### PR TITLE
[XDEBUG] Added remote_connect_back + some refactors

### PR DESCRIPTION
**Pull request by mfdeveloper**
Removed the requirement to pass `XDEBUG_CONFIG: remote_host` and some refactors to more flexibility, with parameters by envoriment variables.

### CODE REVIEW

**Comment by mfdeveloper** [comment]
@andreccosta This Dockerfile/image is maintained yet?

**Comment by andreccosta** [comment]
Hi,

Sorry about the delay getting back to you. This is still maintained. It just so happened that I was on vacation when you sent the PR.

[Docker Hub](https://hub.docker.com/r/andreccosta/wordpress-xdebug/) supposedly has automated builds setup (so that they should happen whenever the wordpress image is updated). But they do seem to lag behind after a few so once in a while they need a build to be manually triggered (which I have just done so the image is again up to date).

About the changes implemented in this pull request I found a few issues:

- Defining an XDebug version in the Dockerfile might prove to be useful in some edge cases but would require some maintenance in the long run? For example 2.6.0 was initially set but 2.6.1 is already available. Ideally I would say this should be something optional (if defined then the set version would be used otherwise the current/default would be installed)
- Using *remote_connect_back* isn't always feasible. In some particular scenarios the container can't automatically discover the host ip (or at least the correct one) and automatically connect back.
This seems to be dependent both on the OS and on the networking setup. In my case running this on Docker for Windows (18.06.1) with the docker-compose setup included in this repo causes exactly that issue. The container cannot talk back to the host and so the XDebug adapter (running in Visual Studio Code in my case) never gets any connection at all.

There is however a solution for using this image and `remote_connect_back`. You can set the environment variable `XDEBUG_CONFIG` to `XDEBUG_CONFIG: remote_connect_back=1` and achieve the desired behavior?

Thank you for your contribution!

**Comment by mfdeveloper** [comment]
Hello @andreccosta !! Thank you so much for your explanation, and I'm sorry for my late response

So, I've tried using `XDEBUG_CONFIG: remote_host=host.docker.internal` environment variable in a `docker-compose.yml`, like described in your **README**, and doesn't works. I've changed to `remote_host=172.17.0.1` and it works!!  My docker version is `18.06.1-ce`.

Using `XDEBUG_CONFIG: remote_connect_back=1` sometimes works, and others do not :cry: 

I'm confuse about this problems. So, I'm using `remote_host=172.17.0.1` for while.

**Comment by andreccosta** [comment]
Hi!

You're right. Apparently `host.docker.internal` is not as "universal" as I thought. I just tried it on a Linux host (running `18.06.1-ce` as well) and it also failed to resolve.
That's a shame. Seems like it's just something that still needs a work-around to work in some platforms.

I'm glad you were able to get it working for you though!

**Pull request merged**
